import { AlertCircle, Check, Sparkles } from "lucide-react";
import type { DoctorInsights } from "@/lib/types";
import { cn } from "@/lib/utils";

interface Props {
  insights: DoctorInsights;
  experienceCount: number;
}

const DIMENSIONS: Array<{ key: keyof Pick<DoctorInsights, "communication" | "listening" | "feeTransparency" | "waitTime">; label: string; hint: string }> = [
  { key: "communication", label: "Communication", hint: "explained things clearly" },
  { key: "listening", label: "Listening", hint: "felt heard, not rushed" },
  { key: "feeTransparency", label: "Fee transparency", hint: "fees clear before the visit" },
  { key: "waitTime", label: "Waiting experience", hint: "reasonable wait time" },
];

function barColor(v: number) {
  if (v >= 80) return "bg-brand-600";
  if (v >= 65) return "bg-brand-400";
  return "bg-peer-500";
}

export default function ReviewInsights({ insights, experienceCount }: Props) {
  return (
    <div className="grid gap-4 lg:grid-cols-2">
      {/* Experience breakdown */}
      <section className="card p-5 sm:p-6" aria-labelledby="breakdown-heading">
        <p className="eyebrow">Experience breakdown</p>
        <h2 id="breakdown-heading" className="mt-1 text-lg font-bold text-slate-900">
          How visits felt
        </h2>
        <p className="mt-1 text-xs text-slate-500">
          Share of experiences positive on each dimension. Patient-experience signals, not
          medical-quality scores.
        </p>
        <dl className="mt-5 space-y-4">
          {DIMENSIONS.map((d) => {
            const v = insights[d.key];
            return (
              <div key={d.key}>
                <div className="flex items-baseline justify-between text-sm">
                  <dt className="font-medium text-slate-800">
                    {d.label} <span className="text-xs font-normal text-slate-500">· {d.hint}</span>
                  </dt>
                  <dd className="font-bold tabular-nums text-slate-900">{v}%</dd>
                </div>
                <div
                  className="mt-1.5 h-2.5 overflow-hidden rounded-full bg-slate-100"
                  role="meter"
                  aria-valuemin={0}
                  aria-valuemax={100}
                  aria-valuenow={v}
                  aria-label={`${d.label}: ${v} percent positive`}
                >
                  <div className={cn("h-full rounded-full transition-all", barColor(v))} style={{ width: `${v}%` }} />
                </div>
              </div>
            );
          })}
        </dl>
      </section>

      {/* AI summary */}
      <section className="card p-5 sm:p-6" aria-labelledby="ai-heading">
        <p className="eyebrow flex items-center gap-1.5 text-brand-700">
          <Sparkles className="h-3.5 w-3.5" aria-hidden />
          AI experience summary
        </p>
        <h2 id="ai-heading" className="mt-1 text-lg font-bold text-slate-900">
          What reviewers keep mentioning
        </h2>
        <p className="mt-3 text-[15px] leading-relaxed text-slate-800">{insights.summary}</p>

        <div className="mt-5 grid gap-4 sm:grid-cols-2">
          <div>
            <p className="text-xs font-bold uppercase tracking-wide text-brand-800">Positive themes</p>
            <ul className="mt-2 space-y-1.5">
              {insights.positiveThemes.map((t) => (
                <li key={t} className="flex items-center gap-2 text-sm text-slate-800">
                  <Check className="h-4 w-4 shrink-0 text-brand-700" aria-hidden />
                  {t}
                </li>
              ))}
            </ul>
          </div>
          <div>
            <p className="text-xs font-bold uppercase tracking-wide text-peer-800">Common concerns</p>
            {insights.concerns.length ? (
              <ul className="mt-2 space-y-1.5">
                {insights.concerns.map((t) => (
                  <li key={t} className="flex items-center gap-2 text-sm text-slate-800">
                    <AlertCircle className="h-4 w-4 shrink-0 text-peer-600" aria-hidden />
                    {t}
                  </li>
                ))}
              </ul>
            ) : (
              <p className="mt-2 text-sm text-slate-500">No recurring concerns yet.</p>
            )}
          </div>
        </div>

        <p className="mt-5 text-xs text-slate-500">
          Based on {experienceCount} demo experiences. Generated by Fable from anonymised,
          moderated reviews and cached. Not medical advice.
        </p>
      </section>
    </div>
  );
}
